##generic functions
if(!isGeneric("preprocess"))
setGeneric("preprocess",function(object,...) standardGeneric("preprocess"), package="HTSanalyzeR")
if(!isGeneric("analyze"))
setGeneric("analyze",function(object,...) standardGeneric("analyze"), package="HTSanalyzeR")
if(!isGeneric("report"))
	setGeneric("report",function(object,...) standardGeneric("report"), package="HTSanalyzeR")
if(!isGeneric("reportAll"))
	setGeneric("reportAll",function(gsca,nwa,...) standardGeneric("reportAll"), package="HTSanalyzeR")
if(!isGeneric("summarize"))
	setGeneric("summarize",function(object,...) standardGeneric("summarize"), package="HTSanalyzeR")
if(!isGeneric("show"))
	setGeneric("show",function(object,...) standardGeneric("show"), package="HTSanalyzeR")

if(!isGeneric("writeHits"))
	setGeneric("writeHits",function(object,...) standardGeneric("writeHits"), package="HTSanalyzeR")
if(!isGeneric("plotGSEA"))
	setGeneric("plotGSEA",function(object,...) standardGeneric("plotGSEA"), package="HTSanalyzeR")
if(!isGeneric("getTopGeneSets"))
	setGeneric("getTopGeneSets",function(object,...) standardGeneric("getTopGeneSets"), package="HTSanalyzeR")
if(!isGeneric("viewGSEA"))
	setGeneric("viewGSEA",function(object,...) standardGeneric("viewGSEA"), package="HTSanalyzeR")

if(!isGeneric("interactome"))
	setGeneric("interactome",function(object,...) standardGeneric("interactome"), package="HTSanalyzeR")
if(!isGeneric("viewSubNet"))
	setGeneric("viewSubNet",function(object) standardGeneric("viewSubNet"), package="HTSanalyzeR")
if(!isGeneric("plotSubNet"))
	setGeneric("plotSubNet",function(object,...) standardGeneric("plotSubNet"), package="HTSanalyzeR")

